package com.projects.digitalpostmasterrest.constant;

public class Constants {
    public static final String RECEIVER_EMPTY = "Receiver cannot be empty";
    public static final String RECEIVER_ADDRESS_EMPTY = "Receiver address cannot be null";
    public static final String PACKAGE_CREATE_ERROR = "Package creation failed";
    public static final String PACKAGE_LIST_EMPTY = "Package list empty";
    public static final String PACKAGE_ID_NULL = "Package id cannot be null";
    public static final String PACKAGE_NOT_FOUND = "Package not found";
    public static final String PACKAGE_DELETE_ERROR = "Package delete request failed";
    public static final String USER_ID_NULL = "User id cannot be empty";
    public static final String USER_NOT_FOUND = "User not found";
    public static final String CONTACT_NO_EMPTY = "Contact no cannot be empty";
    public static final String EMAIL_ADDRESS_EMPTY = "Email address cannot be empty";
    public static final String USER_CREATE_ERROR = "User creation failed";
    public static final String PACKAGE_CREATE_MAIL_SUBJECT = "DIGITAL POST DELIVERY TEAM";
    public static final String USER_LIST_EMPTY = "User list empty";
    public static final String USERNAME_EMPTY = "Username cannot be empty";
    public static final String USER_ALREADY_EXIST = "User already exist for given username or email";
    public static final String LOGIN_ERROR = "Username or password invalided";
    public static final String USER_DELETE_ERROR = "User delete request failed";
    public static final String AGENT_CREATE_ERROR = "Agent creation failed";
    public static final String AGENT_LIST_EMPTY = "Agent list empty";
    public static final String AGENT_ALREADY_EXIST = "Agent already exist for given userId";
    public static final String AGENT_ID_NULL = "Agent id null";
    public static final String AGENT_NOT_FOUND = "Agent not found";
    public static final String AGENT_DELETE_ERROR = "Agent delete request failed";
    public static final String PAYMENT_LIST_EMPTY = "Payment list empty";
    public static final String PAYMENT_CREATE_ERROR = "Payment create request failed";
    public static final String PAYMENT_CREATE_MAIL_SUBJECT = "DIGITAL POST DELIVERY TEAM";
    public static final String DELIVERY_TASK_CREATE_ERROR = "Delivery task creation failed";
    public static final String DELIVERY_TASK_LIST_EMPTY = "Delivery task list empty";
    public static final String DELIVERY_TASK_ID_NULL = "Delivery task ID null";
    public static final String DELIVERY_TASK_NOT_FOUND = "Delivery task not found";
    public static final String DELIVERY_TASK_UPDATED = "Delivery task updated";
    public static final String DELIVERY_TASK_DELETE_ERROR = "Delivery task delete request failed";
    public static final String DELIVERY_TASK_STATUS_UPDATED = "Delivery task status updated";
    public static final String PACKAGE_DELIVERY_TASK_CREATED_MAIL_SUBJECT = "DIGITAL POST DELIVERY TEAM";
    public static final String PAYMENT_AMOUNT_ERROR = "Payment amount error";
    public static final String PAYMENT_NOT_FOUND = "Payment not found";
    public static final String PAYMENT_ID_NULL = "Payment id null";
}
